# kubectl apply -k .
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      component: prometheus
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      containers:
      #
      # Prometheus runs inside the container with a comand line
      # looking like this:
      #
      #   /bin/prometheus --config.file=/etc/prometheus/prometheus.yml
      #   --storage.tsdb.path=/prometheus
      #   --web.console.libraries=/usr/share/prometheus/console_libraries
      #   --web.console.templates=/usr/share/prometheus/consoles
      #
      - name: prometheus
        image: prom/prometheus:v2.14.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
        # This appears to be a CWD of the process, cf. /proc/1/cwd
        # symlink:
        volumeMounts:
        - mountPath: "/prometheus"
          name: "prometheus"

      volumes:
      - name: "prometheus"
        persistentVolumeClaim:
          claimName: "prometheus"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  selector:
    component: prometheus
  ports:
  - port: 9090
    targetPort: 9090
---
#
# We assume here that *.localhost resolves to the local machine.  Following
# URLs should be directed to Prometheus.
#
#     http://prometheus.localhost
#     https://prometheus.localhost
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: prometheus.localhost
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
---
# https://github.com/rancher/local-path-provisioner
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
...
