# kubectl apply -k .
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: prometheus
  template:
    metadata:
      labels:
        component: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  selector:
    component: prometheus
  ports:
  - port: 9090
    targetPort: 9090
---
#
# We assume here that *.localhost resolves to the local machine.  Following
# URLs should be directed to Prometheus.
#
#     http://prometheus.localhost
#     https://prometheus.localhost
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: prometheus.localhost
    http:
      paths:
      - backend:
          serviceName: prometheus
          servicePort: 9090
# https://github.com/rancher/local-path-provisioner
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: prometheus
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   resources:
#     requests:
#       storage: 1Gi
...
