# kubectl apply -k .
namespace: hello-prom
namePrefix: ""
nameSuffix: ""
commonLabels:
  app: "prometheus"
configMapGenerator:
  - name: "config"
    files:
      - "prometheus.yml"
resources:
  - deployment.yaml
